### ISSUE TITLE
How does it work at CIFAR100？

### ISSUE THREAD

**Issue by ZhiyangLiang** [Kedreamix/MAE-for-CIFAR#1]
Hi, have you tried the same for CIFAR100. I'm very curious about the result achieved by MAE on the CIFAR100.

**Comment by Kedreamix** [comment]
@ZhiyangLiang ,I am glad you asked this question. Actually, the solution is very simple. You just need to make some modifications in the "mae_pretrain.py" and "train_classifier.py" files. Specifically, you need to change lines 35 and 36 to use the CIFAR100 dataset, like this:

```python
torchvision.datasets.CIFAR100('data', train=True, download=True, transform=Compose([ToTensor(), Normalize(0.5, 0.5)]))
```

In addition, since CIFAR100 has 100 classes, you also need to modify the "num_classes" parameter in line 47 of "train_classifier.py". Just set it to 100 and you're good to go.
